#if UNITY_EDITOR

using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEngine;

namespace UnityEditor
{
    public class LogChannelAssetPostProcessor : AssetPostprocessor
    {
        private static void OnPostprocessAllAssets(string[] imported, string[] deleted, string[] moved, string[] movedFrom)
        {
            foreach (var path in imported)
            {
                var asset = AssetDatabase.LoadAssetAtPath<LogChannelAsset>(path);
                if (asset != null)
                {
                    LogChannelGenerator.Generate(asset);
                }
            }
        }
    }

    [CustomEditor(typeof(LogChannelAsset))]
    public class LogChannelAssetEditor : Editor
    {
        public override void OnInspectorGUI()
        {
            DrawDefaultInspector();

            EditorGUILayout.Space(8);
            if (GUILayout.Button("⚡  수동enum생성", GUILayout.Height(32)))
                LogChannelGenerator.Generate((LogChannelAsset)target);

            EditorGUILayout.HelpBox(
                "저장(Ctrl+S) 시 Channel enum이 자동 갱신됩니다.\n" +
                "채널 이름은 영문자/숫자/언더스코어(_)만 사용하세요.",
                MessageType.Info);
        }
    }

    public static class LogChannelGenerator
    {
        private static string GetThisScriptDir(
            [System.Runtime.CompilerServices.CallerFilePath] string filePath = "")
            => Path.GetDirectoryName(filePath);

        private static string GetOutputPath()
        {
            string editorDir = GetThisScriptDir();
            string loggerDir = Path.GetDirectoryName(editorDir);
            string fullPath = Path.Combine(loggerDir, "Channel.cs");

            string assetsRelative = "Assets" + fullPath.Substring(Application.dataPath.Length);
            return assetsRelative.Replace('\\', '/');
        }

        public static void Generate(LogChannelAsset asset)
        {
            var builder = new StringBuilder();
            var usedNames = new HashSet<string>();
            int index = 0;
            int skipped = 0;

            builder.AppendLine("// <auto-generated>");
            builder.AppendLine("// * 이 파일은 LogChannelGenerator 스크립트에 의해 생성되었습니다.");
            builder.AppendLine("// * 해당 스크립트는 절대 수동으로 편집하지 마세요.");
            builder.AppendLine("// ! 자동생성 파일이므로, 변경 사항은 덮어쓰여질 수 있습니다.");
            builder.AppendLine("// ? Source: " + asset.name);
            builder.AppendLine("// </auto-generated>");
            builder.AppendLine();
            builder.AppendLine("namespace UnityEngine");
            builder.AppendLine("{");
            builder.AppendLine("    public enum Channel");
            builder.AppendLine("    {");

            foreach (var ch in asset.Channels)
            {
                string safeName = Sanitize(ch.channelName);

                if (string.IsNullOrEmpty(safeName)) { skipped++; continue; }
                if (!usedNames.Add(safeName)) { skipped++; continue; }

                builder.AppendLine($"        {safeName} = {index},");
                index++;
            }

            builder.AppendLine("    }");
            builder.AppendLine("}");

            string outputPath = GetOutputPath();
            string absPath = Path.GetFullPath(Path.Combine(Application.dataPath, "..", outputPath));

            File.WriteAllText(absPath, builder.ToString(), System.Text.Encoding.UTF8);
            LogFormatter.InvalidateHexCache();
            AssetDatabase.ImportAsset(outputPath);
        }

        private static string Sanitize(string name)
        {
            if (string.IsNullOrWhiteSpace(name)) return null;

            var clean = System.Text.RegularExpressions.Regex.Replace(name.Trim(), @"[^\w]", "_");
            if (char.IsDigit(clean[0])) clean = "_" + clean;
            return clean;
        }
    }
}
#endif