// <auto-generated>
// * 이 파일은 LogChannelGenerator 스크립트에 의해 생성되었습니다.
// * 해당 스크립트는 절대 수동으로 편집하지 마세요.
// ! 자동생성 파일이므로, 변경 사항은 덮어쓰여질 수 있습니다.
// ? Source: LogChannelAsset
// </auto-generated>

namespace UnityEngine
{
    public enum Channel
    {
        Default = 0,
        Loader = 1,
        Character = 2,
        Monster = 3,
        Map = 4,
    }
}
